services:
  mongo:
    image: mongo:7
    container_name: l1a-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data_l1a:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
  demo:
    build:
      context: ./demo-app
    container_name: l1a-demo
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://appuser:apppass@mongo:27017/elearning?authSource=admin
      MONGO_DB_NAME: elearning

volumes:
  mongo_data_l1a:
